config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resources :tags, only: [:show, :index] do
    resources :words, only: [:index]
    resources :memos, only: [:index]
  end
  resources :words, expect: [:new, :show]
  resources :memos, expect: [:new, :show]

  root :to => 'homes#top'
  get "home/about" => 'homes#about'

  get 'mypage' => 'users#show', as: 'mypage'
  get 'mypage/edit' => 'users#edit', as: 'edit_mypage'
  patch 'mypage' => 'users#update', as: 'update_mypage'

  get "search" => 'search#search'
  get "memos_sort" => 'search#memosort'
  get "words_sort" => 'search#wordsort'
  get 'pickup' => 'pickup#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :sns_credentials, dependent: :destroy

  has_many :words, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

  # SNS認証関連
  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

    if user.present?
      sns = snscredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { user: user, sns: sns }
    end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    if user.blank?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
    end
    { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    # SNS側から所得した情報とDBを照らし合わせ、登録があるか確認
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    { user: user, sns: sns }
 end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  private

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    # SNS側から取得したデータをハッシュで受け取る
    info = User.find_oauth(@omniauth)
    # user.rbに定義したメソッドでuser登録の有無確認や新規登録を行う
    @user = info[:user]
    if @user.persisted? # userが保存済みかどうか確認
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure # 失敗した時
    redirect_to(root_path) && return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @tags = @user.tags.all
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    if user.update(user_params)
      redirect_to mypage_path, notice: "successfully updated user!"
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="main-top">
	<!--タイトル-->
	<div class="page-ttl">
		<h2 class="page-ttl__mypage">編集ページ</h2>
	</div>

</div>
<div class="main-bottom-mypage">
	<!--会員情報-->
	<div class="mypage">
		<div class="user-info">
		<div class="user-info__info">
		<%= form_with(model: @user, url: update_mypage_path(@user), method: :patch, local: true) do |form| %>
			<table class="table">
				<tr>
					<td>登録名</td>
					<td><%= form.text_field :name, id: "name" %></td>
				</tr>
				<tr>
					<td>登録したメールアドレス</td>
					<td><%= form.text_field :email, autocomplete: "email" %></td>
				</tr>
			</table>
			<div class="mypage-edit-btn">
				<div class="mypage-edit-btn__back">
					<%= link_to 'マイページへ戻る', mypage_path, class: 'btn btn-success' %>
					<%= form.submit '編集内容を保存する', class: "btn btn-danger" %>
				</div>
				<div class="mypage-edit-btn__edit">
				</div>
			</div>
		<% end %>
		</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="main-flash">
	<% if flash[:notice] %>
    	<div class="alert alert-warning main-flash__text">
    		<%= flash[:notice] %>
    	</div>
	<% end %>
</div>

<div class="main-top">

	<!--タイトル-->
	<div class="page-ttl">
		<h2 class="page-ttl__mypage">マイページ</h2>
	</div>

	<!--検索・並び替え窓-->
	<%= render 'search/search_form' %>

</div>

<div class="main-bottom-mypage">
	<div class="mypage">

		<!--word一覧-->
		<div class="mypage__tags">
			<div class="tags">
				<div class="tags__ttl">
				  <p>登録したタグ</p>
				</div>
				<div class="tags__idx">
				  <div class="tag">
					<% @tags.each do |tag| %>
					  <div class="tag__content">
					    <li><%= tag.hashname %></li>
					  </div>
					<% end %>
				  </div>
				</div>
			</div>
		</div>

		<div class="mypage__table">

			<div class="user-info">

				<!--会員情報-->
				<div class="user-info__info">
					<p>ユーザー登録情報</p>
					<table class="table">
						<tr>
							<th>登録名</th>
							<td><%= @user.name %></td>
						</tr>
						<tr>
							<th>登録したメールアドレス</th>
							<td><%= @user.email %></td>
						</tr>
					</table>
				</div>

				<!--編集ボタン-->
				<% if @user.name != "テストユーザー" %>
					<div class="user-info__btn">
						<%= link_to '登録情報編集', edit_mypage_path, class: "btn btn-success" %>
					</div>
				<% end %>
			</div>
		</div>

				<!--登録した単語・メモ数集計-->
		<div class="mypage__sum">
			<div class="histroy">
				<div class="history__text">
					<p>これまでの軌跡</p>
					<table class="table table-stripedx">
						<tr>
							<th>登録した単語数</th>
							<td><%= @user.words.count %></td>
						</tr>
						<tr>
							<th>登録したメモ数</th>
							<td><%= @user.memos.count %></td>
						</tr>
					</table>
				</div>
			</div>
			<div class="links">
				<%= link_to "単語登録へ", words_path, class: "btn btn-success links-btn" %>
				<%= link_to 'メモ登録へ', memos_path, class: "btn btn-warning links-btn" %>
				</div>
			</div>

		</div>


	</div>
</div>