config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resources :tags, only: [:show, :index] do
    resources :words, only: [:index]
    resources :memos, only: [:index]
  end
  resources :words, expect: [:new, :show]
  resources :memos, expect: [:new, :show]

  root :to => 'homes#top'
  get "home/about" => 'homes#about'

  get 'mypage' => 'users#show', as: 'mypage'
  get 'mypage/edit' => 'users#edit', as: 'edit_mypage'
  patch 'mypage' => 'users#update', as: 'update_mypage'

  get "search" => 'search#search'
  get "memos_sort" => 'search#memosort'
  get "words_sort" => 'search#wordsort'
  get 'pickup' => 'pickup#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :hashname, presence: true, length: { maximum: 99 }
  validates :user_id, presence: true

  has_and_belongs_to_many :words, through: :word_tags
  has_many :word_tags
  # has_many :words, through: :word_tags
  # has_many :word_relations, through: :word_tags, source: :word

  has_and_belongs_to_many :memos, through: :memo_tags
  has_many :memo_tags
  # has_many :memos, through: :memo_tags
  # has_many :memo_relations, through: :memo_tags, source: :memo

  belongs_to :user

  def self.search(search, sort_version, model_select)
    if model_select == "tag"
      if sort_version == "new"
        Tag.where(['hashname LIKE ?', "%#{search}%"]).order('created_at desc')
      elsif sort_version == "old"
        Tag.where(['hashname LIKE ?', "%#{search}%"]).order('created_at asc')
      end

    else
      if sort_version == "new"
        Tag.all.order('created_at desc')
      elsif sort_version == "old"
        Tag.all.order('created_at asc')
      end
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @user = current_user
    @tag = Tag.find(params[:id])
    @words = @tag.words
    @word_relations = @tag.word_relations
    @memos = @tag.memos
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/show.html.erb
<div class="main2">
  <div class="leaves">
	<% @word_relations.each do |word| %>
		<% if word.color == "green" %>
			<div class="words" style="background-color: #00bb85;">
		<% elsif word.color == "red" %>
			<div class="words" style="background-color: #f62e36;">
		<% elsif word.color == "blue" %>
			<div class="words" style="background-color: #0078ba;">
		<% elsif word.color == "yellow" %>
			<div class="words" style="background-color: #d7c447;">
		<% elsif word.color == "gray" %>
			<div class="words" style="background-color: #9caeb7;">
		<% end %>
			<div class="words__edit">
				<%= link_to edit_word_path(word), method: :get do %>
					<span class="glyphicon glyphicon-edit" aria-hidden="true" style="color: white;"></span>
				<% end %>
			</div>
			<div class="words__pickup">
					<% if word.pickup == 1 %>
						<span class="glyphicon glyphicon-ok" aria-hidden="true" style="color: white;"></span>
					<% end %>
				</div>
			<div class="words__destroy">
				<%= link_to word_path(word), method: :delete, data: { confirm: "本当に削除しますか？" } do %>
					<span class="glyphicon glyphicon-remove" aria-hidden="true" style="color: white;" ></span>
				<% end %>
			</div>
			<div class="words__content">
				<div class="word-text">
					<div class="word-text__ttl">
						<%= word.name %>
					</div>
					<div class="word-text__body">
						<%= simple_format(word.body) %>
					</div>
				</div>
			</div>
		</div>
	<% end %>

	<!--memo一覧-->
<div class="leaves">
	<% @memo_relations.each do |memo| %>
		<% if memo.color == "green" %>
			<div class="memos" style="background-color: #00bb85;">
		<% elsif memo.color == "red" %>
			<div class="memos" style="background-color: #f62e36;">
		<% elsif memo.color == "blue" %>
			<div class="memos" style="background-color: #0078ba;">
		<% elsif memo.color == "yellow" %>
			<div class="memos" style="background-color: #d7c447;">
		<% elsif memo.color == "gray" %>
			<div class="memos" style="background-color: #9caeb7;">
		<% end %>

				<div class="memos__edit">
					<%= link_to edit_memo_path(memo) do %>
						<span class="glyphicon glyphicon-edit" aria-hidden="true" style="color: white;"></span>
					<% end %>
				</div>
				<div class="memos__pickup">
					<% if memo.pickup == 1 %>
						<span class="glyphicon glyphicon-ok" aria-hidden="true" style="color: white;"></span>
					<% end %>
				</div>
				<div class="memos__destroy">
					<%= link_to memo_path(memo), method: :delete, data: { confirm: "本当に削除しますか？" } do %>
						<span class="glyphicon glyphicon-remove" aria-hidden="true" style="color: white;" ></span>
						<% end %>
				</div>
				<div class="memos__content">
					<%= simple_format(memo.body) %>
				</div>
			</div>
	<% end %>

</div>

</div>