config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resources :tags, only: [:show, :index] do
    resources :words, only: [:index]
    resources :memos, only: [:index]
  end
  resources :words, expect: [:new, :show]
  resources :memos, expect: [:new, :show]

  root :to => 'homes#top'
  get "home/about" => 'homes#about'

  get 'mypage' => 'users#show', as: 'mypage'
  get 'mypage/edit' => 'users#edit', as: 'edit_mypage'
  patch 'mypage' => 'users#update', as: 'update_mypage'

  get "search" => 'search#search'
  get "memos_sort" => 'search#memosort'
  get "words_sort" => 'search#wordsort'
  get 'pickup' => 'pickup#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  has_many :memo_tags
  has_many :tags, through: :memo_tags

  validates :user_id, presence: true
  validates :body, presence: true

  enum color: {
    green: 0,
    red: 1,
    blue: 2,
    yellow: 3,
    gray: 4,
  }

  # ハッシュタグ登録機能関係

  after_create do
    memo = Memo.find_by(id: id)
    tags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)

    tags.uniq.map do |t|
      hashtag = Tag.find_or_create_by(user_id: user_id, hashname: t.downcase.delete('#'))
      memo.tags << hashtag
    end
  end

  before_update do
    memo = Memo.find_by(id: id)
    memo.tags.clear
    tags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)

    tags.uniq.map do |t|
      hashtag = Tag.find_or_create_by(user_id: user_id, hashname: t.downcase.delete('#'))
      memo.tags << hashtag
    end
  end

  # 検索機能

  def self.search(search, sort_version, model_select)
    if model_select == "memo"
      if sort_version == "new"
        Memo.where(['body LIKE ?', "%#{search}%"]).order("created_at desc")
      elsif sort_version == "old"
        Memo.where(['body LIKE ?', "%#{search}%"]).order("created_at asc")
      end

    else
      if sort_version == "new"
        Memo.all.order("created_at desc")
      elsif sort_version == "old"
        Memo.all.order("created_at asc")
      end
    end
  end
end

app/models/memo_tag.rb
class MemoTag < ApplicationRecord
  belongs_to :memo
  belongs_to :tag

  validates :memo_id, presence: true
  validates :tag_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :hashname, presence: true, length: { maximum: 99 }
  validates :user_id, presence: true

  has_and_belongs_to_many :words, through: :word_tags
  has_many :word_tags
  # has_many :words, through: :word_tags
  # has_many :word_relations, through: :word_tags, source: :word

  has_and_belongs_to_many :memos, through: :memo_tags
  has_many :memo_tags
  # has_many :memos, through: :memo_tags
  # has_many :memo_relations, through: :memo_tags, source: :memo

  belongs_to :user

  def self.search(search, sort_version, model_select)
    if model_select == "tag"
      if sort_version == "new"
        Tag.where(['hashname LIKE ?', "%#{search}%"]).order('created_at desc')
      elsif sort_version == "old"
        Tag.where(['hashname LIKE ?', "%#{search}%"]).order('created_at asc')
      end

    else
      if sort_version == "new"
        Tag.all.order('created_at desc')
      elsif sort_version == "old"
        Tag.all.order('created_at asc')
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :sns_credentials, dependent: :destroy

  has_many :words, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

  # SNS認証関連
  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

    if user.present?
      sns = snscredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { user: user, sns: sns }
    end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    if user.blank?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
    end
    { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    # SNS側から所得した情報とDBを照らし合わせ、登録があるか確認
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    { user: user, sns: sns }
 end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
  has_many :word_tags
  has_many :tags, through: :word_tags

  validates :user_id, presence: true
  validates :name, presence: true
  validates :body, presence: true

  enum color: {
    green: 0,
    red: 1,
    blue: 2,
    yellow: 3,
    gray: 4,
  }

  # ハッシュタグ登録機能関係

  after_create do
    word = Word.find_by(id: id)
    tags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)

    tags.uniq.map do |t|
      hashtag = Tag.find_or_create_by(user_id: user_id, hashname: t.downcase.delete('#'))
      word.tags << hashtag
    end
  end

  before_update do
    word = Word.find_by(id: id)
    word.tags.clear
    tags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)

    tags.uniq.map do |t|
      hashtag = Tag.find_or_create_by(user_id: user_id, hashname: t.downcase.delete('#'))
      word.tags << hashtag
    end
  end

  def self.search(search, sort_version, model_select)
    if model_select == "word"
      if sort_version == "new"
        Word.where(['name LIKE ? OR body LIKE ?', "%#{search}%", "%#{search}%"]).order('created_at desc')
      elsif sort_version == "old"
        Word.where(['name LIKE ? OR body LIKE ?', "%#{search}%", "%#{search}%"]).order('created_at asc')
      end

    else
      if sort_version == "new"
        Word.all.order('created_at desc')
      elsif sort_version == "old"
        Word.all.order('created_at asc')
      end
    end
  end
end

app/models/word_tag.rb
class WordTag < ApplicationRecord
  belongs_to :word
  belongs_to :tag

  validates :word_id, presence: true
  validates :tag_id, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/memo_tags_helper.rb
module MemoTagsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
  def render_with_tags(body)
    body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { link_to word, "/memo/tag/#{hashname.delete('#')}" }.html_safe
  end
end

app/helpers/pickup_helper.rb
module PickupHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/word_tags_helper.rb
module WordTagsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_header1.html.erb
<div class="header1">
	<div class="header1__lg">
		<%= link_to root_path do %>
			<div class="logo"></div>
		<% end %>
	</div>
	<div class="btn1">
		<li class="btn1__list">
			<%= link_to 'about', home_about_path, class: "btn btn-default" %>
		</li>
		<li class="btn1__list">
			<%= link_to '新規登録', new_user_registration_path, class: "btn btn-default" %>
		</li>
		<li class="btn1__list">
			<%= link_to 'ログイン', new_user_session_path, class: "btn btn-default" %>
		</li>
	</div>
</div>

app/views/layouts/_header2.html.erb
<div class="header1">
	<div class="header1__lg">
		<div class="logo"></div>
	</div>
	<div class="btn1">
			<li class="dropdown btn1__list">
				<a href='#' class="btn btn-default" data-toggle="dropdown" role="button" aria-expanded="false">マイメニュー  <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li role="presentation"><%= link_to 'マイページ', mypage_path(current_user) %></li>
					<li role="presentation"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
				</ul>
			</li>
			<li class="btn1__list"><%= link_to 'Word', words_path, class: "btn btn-success" %></li>
			<li class="btn1__list"><%= link_to 'Memo', memos_path, class: "btn btn-warning" %></li>
			<li class="btn1__list"><%= link_to 'Pickup', pickup_path, class: "btn btn-success" %></li>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoTREE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://kit.fontawesome.com/36666c5f50.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "layouts/header2" %>
    <% else %>
      <%= render "layouts/header1" %>
    <% end %>
    <%= yield %>
  </body>
</html>